version: "3"

tasks:
  setup:
    cmds:
      - mkdir build
    silent: true

  build:
    deps: [setup]
    cmds:
      - odin build src/ -out=build/beorn.exe -o:none -debug
    silent: true

  run:
    deps: [setup]
    cmds:
      - odin run src/ -out=build/beorn.exe -debug
    silent: true

  test:
    deps: [setup]
    cmds:
      # - cmd: odin test tests/ -out=build/beorn-test.exe -all-packages -define:ODIN_TEST_PROGRESS_WIDTH=0 -define:ODIN_TEST_SHORT_LOGS=true -define:ODIN_TEST_NAMES=test_cpu.opcode_0xc7
      - cmd: odin test tests/ -out=build/beorn-test.exe -all-packages -define:ODIN_TEST_PROGRESS_WIDTH=0 -define:ODIN_TEST_SHORT_LOGS=true
        ignore_error: true
    silent: true
